version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    cache:
        blobdescriptor: redis
    filesystem:
        rootdirectory: /tmp/registry-dev
    maintenance:
        uploadpurging:
            enabled: false
auth:
    token:
        realm: https://127.0.0.1:8080/auth
        service: Docker registry
        issuer: netease auth server
        rootcertbundle: /go/src/github.com/docker/distribution/certs/domain.crt 
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    tls:
        certificate: /go/src/github.com/docker/distribution/certs/domain.crt 
        key: /go/src/github.com/docker/distribution/certs/domain.key
    #debug:
        #addr: localhost:5001
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
